server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: yyn-order
  cloud:
    config:
    ###读取版本环境
      profile: dev
      discovery:
        ###读取config-server环境 写eureka中configserver名称或者写死服务地址+端口号
        service-id: config-server
        ###开启读取权限
        enabled: true

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
user:
  age: 20