server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: yyn-member

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh