logging:
  level:
    root: debug
gate-way-prefix: /api/v1 
server:
  port: ${PORT:8970}

spring:
  application:
    name: msa-gate
  jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
  #限制了请求的文件大小:每个文件的配置最大为1,048,576 bytes=1M，单次请求的文件的总数不能大于10Mb
  servlet:
      multipart:
          max-file-size: 100MB
          max-request-size: 50MB
  # Redis configuration
  redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PSWD:beyondsoft}
      #默认使用db2
      database: ${REDIS_DB_NO:7}
  cloud:
    gateway:
       ### 可以定义一些共同的filter，对所有路由都起作用 根据ip限制流量
       default-filters:
       ### 默认true 启动网关       enabled: true
       routes:
        ### 这个路由的唯一id，不定义的话为一个uuid
        - id: cashier               
          ### http请求为lb://前缀 + 服务id； 
          ### ws请求为lb:ws://前缀 + 服务id；表示将请求负载到哪一个服务上     
          uri: lb://FNB-CASHIER
          ### 表示这个路由的请求匹配规则，只有符合这个规则的请求才会走这个路由。为一个数组，每个规则为并且的关系
          predicates:
              ### 1. name：规则名称，目前有10个，有Path，Query，Method，Header，After，Before，Between，Cookie，Host，RemoteAddr 
              ### 2. args：参数key-value键值对
          - Path=${gate-way-prefix}/cashier/**
          ### 请求转发前的filter，为一个数组
          filters: 
          - StripPrefix=3
          - name: RequestRateLimiter
            args: 
              ### 允许用户每秒处理多少个请求
              redis-rate-limiter.replenishRate: 20
              ### 令牌桶的容量，允许在一秒钟内完成的最大请求数
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"
          ###  这个路由的执行order 越小越优先
          ### order: 1
          
         # Websocket route
        - id: websocket_route
          uri: lb:ws://fnb-cashier
          predicates:
          - Path=${gate-way-prefix}/websocket/member/**
          filters: 
          - StripPrefix=4
        
        - id: admin               
          uri: lb://fnb-admin
          predicates:
          - Path=${gate-way-prefix}/admin/**
          filters: 
          - StripPrefix=3
          - name: RequestRateLimiter
            args: 
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"
          
        - id: shop               
          uri: lb://fnb-shopmgr
          predicates:
          - Path=${gate-way-prefix}/shop/**
          filters: 
          - StripPrefix=3
          - name: RequestRateLimiter
            args: 
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"
          
        - id: payment               
          uri: lb://msa-payment
          predicates:
          - Path=${gate-way-prefix}/payment/**
          filters: 
          - StripPrefix=3
          - name: RequestRateLimiter
            args: 
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"
          
        - id: crm               
          uri: lb://msa-crm
          predicates:
          - Path=${gate-way-prefix}/crm/**
          filters: 
          - StripPrefix=3
          - name: RequestRateLimiter
            args: 
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"
          
        - id: sms               
          uri: lb://webservice-sms
          predicates:
          - Path=${gate-way-prefix}/sms/**
          filters: 
          - StripPrefix=3
          - name: RequestRateLimiter
            args: 
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"

###注册到注册中心
eureka:
  instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        # true-注册时使用ip  false - 主机名
        prefer-ip-address: ${PREFER_IP_ADDRESS:true}
        # 指定此实例的ip
        ip-address: ${IP_ADDRESS:127.0.0.1}
  client:
    serviceUrl:
        defaultZone: http://${REGISTRY_NAME:beyondSoft}:${REGISTRY_PASS:beyondSoft2018.com}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

ribbon:
  eureka:
    enabled: true

###开启压缩      
feign: 
  client:
    config:
       #服务名，填写default为所有服务
      default:       
        # 连接时间   
        connectTimeout: 5000
        # 超时时间
        readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request: 
      enabled: true 
      ###配置压缩文档类型及最小压缩的文档大小
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

##开启所有端点
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"

