server:
   port: 8007
spring:
   application:
      name: consul-order
   ####consul注册中心地址
   cloud:
      consul:
         host: localhost
         port: 8500
         discovery:
         ###服务地址指定生成
             register: true
             hostname: 192.168.3.2
debug: true