server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: yyn-member
  zipkin:
    base-url: http://localhost:9411/
  ###全部采集
  sleuth:
    sampler:
      probability: 1.0
  
feign:
  hystrix:
    enabled: true
    
