server:
   port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: config-server
  rabbitmq:
       host: localhost
       port: 5672
       username: guest
       password: guest
  cloud:
    config:
      server:
       git:
         ### git地址
         uri: https://gitee.com/sybsybsyb/distributed_configuration_file.git
         search-paths:
          ### 加载文件目录
          - fast-config
      ###分支
      label: master
#### git上配置文件规范：服务名称-环境.properties

##开启所有端点 开启通过监控自动刷新集群 
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
       